language: groovy

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
  - ~/.m2

env:
  global:
    - JAVA_OPTS=-Xmx512m
    - GROUP_ID="pl.warsjawa"
    - ARTIFACT="ui"
    - VERSION=CD-${TRAVIS_BUILD_NUMBER}
    - RUNDECK_URL="http://rundeck.warsjawa.uservices.pl:4440"
    - RUNDECK_JOB_ID="da97ec93-39d1-48c4-a421-4f63304c1628"
    - RUNDECK_JOB_ARGS="-groupId ${GROUP_ID} -artifactId ${ARTIFACT} -version ${VERSION}"
    - RUNDECK_AUTH_TOKEN="ZnpwK9YT5w0CJDuVyzMa7im5uJIEtJK9"
script:
  - ./gradlew build --stacktrace

after_success:
  - ./gradlew clean build uploadArchives
  - ./gradlew test jacocoTestReport coveralls -Pcoverage
  - ./gradlew uptodate
